version: '3.8'

services:
  npm-moony:
    container_name: npm-moony
    build: .
    ports:
      - "4873:4873"
    volumes:
      - verdaccio_data:/verdaccio

volumes:
  verdaccio_data:
    driver: local
